FROM python:3.10-slim

WORKDIR /app

COPY requirements/train.txt /app/requirements/train.txt

RUN pip install --no-cache-dir -r /app/requirements/train.txt

COPY src /app/src
COPY configs /app/configs

ENV PYTHONPATH=/app:/app/src

CMD ["python", "/app/src/train.py"]
